#!/bin/bash
#
# Generate coding-standard.md from development_guidline.yaml
#
# Extracts only coding_standards and directory_structure sections
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
YAML_FILE="${SCRIPT_DIR}/development_guidline.yaml"
OUTPUT_FILE="${SCRIPT_DIR}/coding-standard.md"

# Check if yq is available
if ! command -v yq &> /dev/null; then
    echo "Error: yq is not installed"
    exit 1
fi

# Check if input file exists
if [ ! -f "$YAML_FILE" ]; then
    echo "Error: $YAML_FILE not found"
    exit 1
fi

# Generate Markdown
cat > "$OUTPUT_FILE" << 'EOF'
# Coding Standard for Infrastructure

> **Note**: This file is auto-generated from `development_guidline.yaml`.
> Do not edit this file directly. Edit the YAML file instead and run `./generate-coding-standard.sh`.

EOF

# Extract directory_structure
echo "## Directory Structure" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

yq eval '.directory_structure.infrastructure.rules[] | "* " + .body' "$YAML_FILE" >> "$OUTPUT_FILE"

# Add note if exists
NOTE=$(yq eval '.directory_structure.infrastructure.rules[0].note' "$YAML_FILE")
if [ "$NOTE" != "null" ]; then
    echo "" >> "$OUTPUT_FILE"
    echo "$NOTE" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"

# Extract coding_standards sections
SECTIONS=$(yq eval '.coding_standards | keys | .[]' "$YAML_FILE")

for section in $SECTIONS; do
    # Convert section name to title case
    SECTION_TITLE=$(echo "$section" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1')

    echo "## $SECTION_TITLE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

    # Extract rules for this section
    yq eval ".coding_standards.$section.rules[] | \"* \" + .body" "$YAML_FILE" >> "$OUTPUT_FILE"

    echo "" >> "$OUTPUT_FILE"
done

echo "✅ Generated: $OUTPUT_FILE"
